apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
  namespace: grupo2
type: Opaque
data:
  username: ZGVmYXVsdF91c2VyX3l1WXFHWF9XX19kUzN5cDFrdDE=
  password: azNUZkNXZVlqWEVnRURNMkxaM0JaNkdiUU9OMnZfS1g=
