{
 "title": "Dashoard_SistemasDistribuidos_Grupo2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Visão Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mongodb_connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"grupo2\", deployment=\"produtor-deployment\"}",
     "legendFormat": "Produtores"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"grupo2\", deployment=\"consumidor-deployment\"}",
     "legendFormat": "Consumidores"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"grupo2\", deployment=\"api-deployment\"}",
     "legendFormat": "API"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"grupo2\", deployment=\"ui-deployment\"}",
     "legendFormat": "UI"
    }
   ]
  },
  {
   "title": "RabbitMQ Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"rabbit\", namespace=\"grupo2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estado API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_db_connection_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estado da Base de Dados",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  { "title": "Fluxo de Dados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Produção vs Consumo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(producer_messages_created_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(consumer_messages_processed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lag(Mensagens em Espera)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"real_time_data\",vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencia y Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latencia Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(consumer_message_processing_duration_seconds_bucket[5m]))",
     "legendFormat": "Pior caso - 95%"
    },
    {
     "expr": "rate(consumer_message_processing_duration_seconds_sum[1m]) / rate(consumer_message_processing_duration_seconds_count[1m])",
     "legendFormat": "Media"
    }
   ]
  },
  {
   "title": "Latência API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(api_request_duration_seconds_bucket[5m])",
     "legendFormat": "API - {{pod}}"
    }
   ]
  },
  { "title": "Infraestrutura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "mongodb_op_counters_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type=\"insert\", namespace=\"grupo2\"}[1m])",
     "legendFormat": "Escrituras (Consumidor)"
    },
    {
     "expr": "rate(mongodb_op_counters_total{type=\"query\", namespace=\"grupo2\"}[1m])",
     "legendFormat": "Lecturas (API)"
    }
   ]
  },
  {
   "title": "mongodb_connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\", namespace=\"grupo2\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "mongodb_connections{state=\"available\", namespace=\"grupo2\"}",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Saturação Producer ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"produtor-deployment.*\", container!=\"\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"grupo2\", pod=~\"produtor-deployment.*\", container=\"produtor\"}) by (pod) / 1024 / 1024",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "% de um Core",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"produtor-deployment.*\", container!=\"POD\"}[5m])) * 100",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  },
  { "title": "Saturação Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"consumidor-deployment.*\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "Consumer - {{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"grupo2\", pod=~\"consumidor-deployment.*\", container=\"consumidor\"}) by (pod) / 1024 / 1024",
     "legendFormat": "Consumer - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "% de um Core",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"consumidor-deployment.*\", container!=\"POD\"}[5m])) * 100",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  },
  { "title": "Saturação API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"api-deployment.*\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "API - {{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"grupo2\", pod=~\"api-deployment.*\", container=\"api\"}) by (pod) / 1024 / 1024",
     "legendFormat": "API - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "% de um Core",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"api-deployment.*\", container!=\"POD\"}[5m])) * 100",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  },
  { "title": "Saturação UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"ui-deployment.*\", container!=\"POD\"}[5m])) by (pod)",
     "legendFormat": "UI - {{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"grupo2\", pod=~\"ui-deployment.*\", container=\"ui\"}) by (pod) / 1024 / 1024",
     "legendFormat": "UI - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "% de um Core",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"grupo2\", pod=~\"ui-deployment.*\", container!=\"POD\"}[5m])) * 100",
     "legendFormat": "Produtor - {{pod}}"
    }
   ]
  }
 ]
}