{
 "title": "Main Dashboard - Distribuited Systems",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Visão Geral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estado da Base de Dados",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Estado API",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "api_db_connection_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Consumidores Ativos",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rabbitmq_queue_consumers", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Fluxo de Dados",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produção vs Consumo",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(producer_messages_created_total[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(consumer_messages_processed_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lag(Mensagens em Espera)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "rabbitmq_queue_messages", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Latencia y Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latencia Consumer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(consumer_message_processing_duration_seconds_bucket[5m]))",
       "legendFormat": "Pior caso - 95%"
      },
      {
       "expr": "rate(consumer_message_processing_duration_seconds_sum[1m]) / rate(consumer_message_processing_duration_seconds_count[1m])",
       "legendFormat": "Media"
      }
     ]
    },
    {
     "title": "Latência API",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(api_request_duration_seconds_bucket[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Infraestrutura",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "mongodb_op_counters_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mongodb_connections",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "mongodb_connections", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}