# k8s-config/2-aplicacoes/consumidor.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor
  template:
    metadata:
      labels:
        app: consumidor
    spec:
      containers:
        - name: consumidor
          # IMAGEM CORRIGIDA:
          image: kingdavid08/consumer:46
          ports:
            # A porta do Uvicorn (do Dockerfile)
            - containerPort: 8000
          
          # --- LIGAÇÃO À INFRAESTRUTURA (Passo 1) ---
          env:
            # Constrói a URL de conexão completa para o RabbitMQ,
            # injetando o utilizador e a senha a partir do Secret.
            # O formato é: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbit-service:5672/
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbit-service:5672/"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            
            # Ligação ao MongoDB
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: consumidor-service # A UI usará este nome de DNS
spec:
  # Acessível apenas DENTRO do cluster
  type: ClusterIP
  selector:
    app: consumidor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000