apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumidor
  template:
    metadata:
      labels:
        app: consumidor
    spec:
      containers:
        - name: consumidor
          image: kingdavid08/consumer:52
          
          # --- CORREÇÃO ---
          # Encapsular o comando com 'sh -c' para evitar a expansão de variáveis
          # pelo shell do container, garantindo que o Python (via uvicorn) receba os valores corretos.
          command: ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port 8000"]
          
          ports:
            - containerPort: 8000
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            
            # 2. Variáveis do MongoDB (necessárias para o config.py)
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
                  
            # 3. Kubernetes injeta o nome da fila
            - name: QUEUE_NAME
              value: "real_time_data"
---
apiVersion: v1
kind: Service
metadata:
  name: consumidor-service 
spec:
  type: ClusterIP
  selector:
    app: consumidor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000