apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: consumidor
  template:
    metadata:
      labels:
        app: consumidor
    spec:
      containers:
        - name: consumidor
          image: kingdavid08/consumer:56
          
          # O consumidor agora é um script Python, não um servidor web.
          # O comando executa o módulo 'src.main' como um script.
          # As portas não são mais necessárias.
          command: ["python", "-m", "src.main"]
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            
            # 2. Variáveis do MongoDB (necessárias para o config.py)
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
                  
            # 3. Kubernetes injeta o nome da fila
            - name: QUEUE_NAME
              value: "real_time_data"