apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumidor-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: consumidor
  template:
    metadata:
      labels:
        app: consumidor
      # Anotações para o Prometheus descobrir e recolher métricas deste pod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001" # A porta que definimos no código Python
    spec:
      containers:
        - name: consumidor
          image: kingdavid08/consumer:69
          
          # O consumidor agora é um script Python, não um servidor web.
          # O comando executa o módulo 'src.main' como um script.
          # As portas não são mais necessárias.
          command: ["python", "-m", "src.main"]
          ports:
            - containerPort: 8001
              name: metrics
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            
            # 2. Variáveis do MongoDB (necessárias para o config.py)
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_NAME
              value: "projeto_sd"
            - name: COLLECTION_NAME
              value: "dados_corrida"
            - name: QUEUE_NAME
              value: "real_time_data"