# k8s-config/2-aplicacoes/produtor.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor
  template:
    metadata:
      labels:
        app: produtor
    spec:
      containers:
        - name: produtor
          # IMAGEM CORRIGIDA:
          image: kingdavid08/producer:24
          
          # --- LIGAÇÃO À INFRAESTRUTURA (Passo 1) ---
          env:
            # Ligação ao RabbitMQ
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: rabbit-config
                  key: RABBITMQ_URL
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS 