apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor
  template:
    metadata:
      labels:
        app: produtor
    spec:
      containers:
        - name: produtor
          image: kingdavid08/producer:51
          
          command: ["sh", "-c", "python Producer.py"]
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            - name: RABBITMQ_HOST
              value: "rabbit-service"
            
            # 2. Kubernetes injeta o nome da fila
            - name: QUEUE_NAME
              value: "real_time_data"
            # 3. Runner ID (default: nome do Pod)
            - name: RUNNER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name