apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-deployment
  namespace: grupo2
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: produtor
  template:
    metadata:
      labels:
        app: produtor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-sd-1
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: produtor
          image: kingdavid08/producer:138
          
          command: ["sh", "-c", "python Producer.py"]
          
          ports:
            - containerPort: 8001
              name: metrics
          
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
            - name: RABBITMQ_HOST
              value: "rabbitmq-cluster.rabbitmq-system.svc.cluster.local"
            
            # 2. Kubernetes injeta o nome da fila
            - name: QUEUE_NAME
              value: "real_time_data"
