apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: produtor
  template:
    metadata:
      labels:
        app: produtor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: produtor
          image: kingdavid08/producer:80
          
          command: ["sh", "-c", "python Producer.py"]
          
          ports:
            - containerPort: 8001
              name: metrics
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          
          env:
            # 1. Kubernetes injeta as credenciais no ambiente
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: RABBITMQ_PASS
            - name: RABBITMQ_HOST
              value: "rabbit-service"
            
            # 2. Kubernetes injeta o nome da fila
            - name: QUEUE_NAME
              value: "real_time_data"
