# k8s-config/2-aplicacoes/ui.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: grupo2
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - k3s-sd-1
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: ui
          # IMAGEM CORRIGIDA: Aponta para a tag :latest que o GitHub Actions vai criar
          image: kingdavid08/ui:85
          ports:
            # A porta do seu 'server.js' (do DockerFile)
            - containerPort: 3000
              name: http
            - containerPort: 8001
              name: metrics
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: grupo2
spec:
  # Expõe o serviço fora do cluster
  type: NodePort
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000       # Porta interna do serviço
      targetPort: 3000 # Porta do contentor
      # Aceda à UI em http://localhost:30102
      nodePort: 30102
      name: http