# k8s-config/2-aplicacoes/ui.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          # IMAGEM CORRIGIDA: Aponta para a tag :latest que o GitHub Actions vai criar
          image: kingdavid08/ui:68
          ports:
            # A porta do seu 'server.js' (do DockerFile)
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  # Expõe o serviço fora do cluster
  type: NodePort
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000       # Porta interna do serviço
      targetPort: 3000 # Porta do contentor
      # Aceda à UI em http://localhost:30100
      nodePort: 30100